version: 2.1
orbs:
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  build:
    docker:
      - image: cimg/node:20.6.0
    steps:
      - checkout
      - run:
          name: Install rsync
          command: |
            sudo apt-get update
            sudo apt-get install -y rsync
      - run:
          name: Debug Home Directory
          command: |
            echo "Contents of $HOME:"
            ls -la $HOME
      - run:
          name: Copy all files and folders to /home/circleci/project/alco24
          command: rsync -avz $HOME/project/ /home/circleci/project/alco24
      - run:
          name: Install Dependencies
          command: |
            cd /home/circleci/project/alco24/front_expensive
            npm install
            cd /home/circleci/project/alco24/back_expensive
            npm install
      - run:
          name: Build Frontend and Backend
          command: |
            cd /home/circleci/project/alco24/front_expensive
            npm run build # Конфигурация сборки фронтенда
            cd /home/circleci/project/alco24/back_expensive
            npm run build # Конфигурация сборки бэкенда
  push_frontend:
    docker:
      - image: cimg/base:2023.08
    steps:
      - attach_workspace:
          at: /home/circleci/project/alco24/
      - run:
          name: Debug The Directory
          command: |
            echo "Contents of Workspace:"
            ls -la /home/circleci/project/alco24
      - run:
          name: Push Frontend to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker build -t demodynamics/front_expensive:1.0.0 /home/circleci/project/alco24/front_expensive/
            docker push demodynamics/front_expensive:1.0.0

  deploy_frontend:
    docker:
      - image: cimg/base:2023.08
    steps:
      - kubernetes/install-kubectl
      - attach_workspace:
          at: /home/circleci/project/alco24/
      - run:
          name: Copy kubeconfig for Frontend Deployment
          command: cp /home/circleci/project/alco24/kubeconfig.yaml $HOME/.kube/config
      - run:
          name: Use kubeconfig for Frontend Deployment
          command: kubectl apply -f /home/circleci/project/alco24/deployment.yaml # Укажите путь к файлу деплоя фронтенда

workflows:
  build-deploy:
    jobs:
      - build
      - push_frontend:
          requires:
            - build
      - deploy_frontend:
          requires:
            - push_frontend
